vtk_module(vtkRenderingLabel
  GROUPS
    Rendering
  TEST_DEPENDS
    vtkIOXML
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkRendering
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkRenderingCore
    vtkRenderingFreeType
    vtkRenderingOpenGL2
  PRIVATE_DEPENDS
    vtkCommonMath
    vtkCommonSystem
    vtkCommonTransforms
    vtkFiltersGeneral
    vtkImagingCore
    vtkIOImage
    vtkIOXML
  )
