name: build-ubuntu-20.04

on: workflow_dispatch
#on: push

jobs:

  build-vtk:
    name: Build VTK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: bash ./zz_scripts/build-clean-os-ubuntu-20.04.sh
        # TODO: Upload logs even if the build fails.
      - name: Archive and upload vtk-build-env.txt
        uses: actions/upload-artifact@v2
        with:
          name: vtk-build-env.txt
          path: build-output/vtk-build-env.txt
      - name: Archive and upload vtk-cmake-variables-values.txt
        uses: actions/upload-artifact@v2
        with:
          name: vtk-cmake-variables-values.txt
          path: build-output/vtk-cmake-variables-values.txt
      - name: Archive and upload build.log
        uses: actions/upload-artifact@v2
        with:
          name: build.log
          path: build-output/build.log
      - name: Archive and upload binary package artifact
        uses: actions/upload-artifact@v2
        with:
          # TODO: Adjust version in CMakeLists.txt or in build script (cpack invocation) and here.
          name: daswb-depends_vtk-9.0.1_ubuntu-20.04.tar.gz
          path: build-output/daswb-depends_vtk-9.0.1_ubuntu-20.04.tar.gz
